pipeline {
    agent {label 'ec2-app'}

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'rds_redis']], userRemoteConfigs: [[url: 'https://github.com/mahmoud254/jenkins_nodejs_example.git']]])
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t elnabatshy/nodejs:v1.0 -f dockerfile .'
            }
        }
        stage('Artifact') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh 'docker login -u $USERNAME -p $PASSWORD'
                sh 'docker push elnabatshy/nodejs:v1.0'
                }
            }
        }
        stage('CD') {
            steps {
                sh 'docker run -d -p 3000:3000 elnabatshy/nodejs:v1.0'
            }
        }
    }
}