pipeline {
    agent any

    stages {
        stage('preparation') {
            steps {
                git 'https://github.com/mahmoud254/jenkins_nodejs_example.git'
            }
        }
        stage('CI') {
            steps {
                sh 'docker build -t elnabatshy/nodejs:v1.0 -f dockerfile .'
            }
        }
        stage('build') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh 'docker login -u $USERNAME -p $PASSWORD'
                sh 'docker push elnabatshy/nodejs:v1.0'
                }
            }
        }
        stage('CD') {
            steps {
                sh 'ssh -i {ssh-file} user@application'
                sh 'docker run -d -p 3000:3000 elnabatshy/nodejs:v1.0'
            }
        }
    }
}
